services:
  app:
    # image: node:lts-buster-slim
    container_name: Preentrega1-Urdaneta
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    
    # working_dir: /e-commerce
    # command: bash -c "npm i "
